name: weatherbeing
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.26.0
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_auth: ^4.17.7
  flutter_native_splash: ^2.4.1
  http: ^1.2.2
  intl: ^0.17.0
  permission_handler: ^11.3.1
  auto_size_text: ^3.0.0
  test: ^1.16.0
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  syncfusion_flutter_charts: ^21.1.35
  url_launcher: ^6.1.7
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/main.png
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/sex.png
    - assets/images/bmi.png
    - assets/images/man.png
    - assets/images/woman.png
    - assets/images/map.png
  


flutter_native_splash:
  color: "#FAAEC3"
  image: assets/images/logo.png
  android_gravity: center
  android_12:
    image: assets/images/logo.png
    android_gravity: center
  android: true
  ios: true
